### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by JeliHacker** [portabletext/react-native-portabletext#1]
Similar to the issue posted [here:](https://github.com/portabletext/react-portabletext/issues/13). 

```
import {PortableText, toPlainText, PortableTextComponents} from '@portabletext/react'
import type {PortableTextBlock} from '@portabletext/types'

...

const blocks = [
  {
    "_key": "13adecf97214",
    "_type": "block",
    "children": [
      {
        "_key": "0914e35531130",
        "_type": "span",
        "marks": [],
        "text": "Under IDEA law, an "
      },
      {
        "_key": "41ac34580ba5",
        "_type": "span",
        "marks": [
          "c2a8881bef79"
        ],
        "text": "IEP"
      },
      {
        "_key": "734c9644b508",
        "_type": "span",
        "marks": [],
        "text": " is a legal..."
      }
    ],
    "markDefs": [
      {
        "_key": "c2a8881bef79",
        "_type": "link",
        "href": "https://www.../"
      }
    ],
    "style": "normal"
  }
]
```

...

`<PortableText value={blocks} />`

Gives error:
Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in p (created by normal)
    in normal (created by ae)
    in ae (created by WordViewBody)
    in RCTView (created by View)
    in View (created by WordViewBody)
    in WordViewBody (created by WordView)
    in RNCSafeAreaView
    in Unknown (created by WordView)
    in WordView (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by Navigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Navigation)
    in Navigation (created by App)
    in WordContextProvider (created by App)
    in BookmarkContextProvider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:52:4 in showErrorDialog
at hooks/useTerms.ts:36:16 in <anonymous>

**Comment by rexxars** [comment]
Looks like you're importing from `@portabletext/react`, not `@portabletext/react-native`?

**Comment by JeliHacker** [comment]
That was it, thanks!
