### ISSUE TITLE
Support for React Native 0.72

### ISSUE THREAD

**Issue by xnejp03** [portabletext/react-native-portabletext#28]
Updating to RN 0.72 results in npm error

```
Could not resolve dependency:
npm ERR! peer react-native@"^0.66 || ^0.67 || ^0.68 || ^0.69 || ^0.70 || ^0.71" from @portabletext/react-native@1.0.0
```

**Comment by alice-ang** [comment]
I have this problem as well as I am using Expo SDK 49 which requires React Native 0.72.3
![image](https://github.com/portabletext/react-native-portabletext/assets/24763251/beb89c3f-4ce2-4c29-adaf-d5693db656f0)
